#!/usr/bin/perl
use File::Glob ':glob';
@exefiles = bsd_glob("Assets/Editor/PostprocessBuildPlayer_*", GLOB_NOCASE);
foreach $file(@exefiles)
{
  system($file, $ARGV[0], $ARGV[1], $ARGV[2], $ARGV[3], $ARGV[4], $ARGV[5], $ARGV[6]);
}
